services:
  api1: &api
    image: gabrielluciano/rinha-2023-api-quarkus-native:1.0
    hostname: api1
    depends_on:
      - database
    environment:
      - HTTP_PORT=8080
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2:
    <<: *api
    hostname: api2
    environment:
      - HTTP_PORT=8081
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  database:
    image: postgres:15.4
    hostname: database
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRES_DB=quarkus
    network_mode: "host"
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'
